version: 2

jobs:
  macos:
    macos:
      xcode: "9.2"
    steps:
      - run: brew install mysql
      - run: brew services start mysql
      - run: sleep 3 && mysqladmin -uroot create test
      - checkout
      - run: swift build
      - run: echo "CREATE DATABASE vapor_test" | mysql -uroot
      # - run: swift build -c release
      - run: swift test

  linux:
    docker:
      - image: norionomura/swift:swift-4.1-branch
      - image: mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: test
          # MYSQL_ROOT_HOST: %
          MYSQL_USER: foo
          MYSQL_PASSWORD: bar
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install -yq libssl-dev pkg-config
      - run: swift build
      - run: swift test
      - run: swift build -c release

workflows:
  version: 2
  tests:
    jobs:
     # - macos
      - linux

