#if !canImport(ObjectiveC)
import XCTest

extension MySQLKitTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MySQLKitTests = [
        ("testSQLKitBenchmark", testSQLKitBenchmark),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(MySQLKitTests.__allTests__MySQLKitTests),
    ]
}
#endif
